#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-JsonPath
Version  : 2.4.0
Release  : 1
URL      : https://github.com/json-path/JsonPath/archive/json-path-2.4.0.tar.gz
Source0  : https://github.com/json-path/JsonPath/archive/json-path-2.4.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.jar
Source2  : https://repo.maven.apache.org/maven2/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-JsonPath-data = %{version}-%{release}
Requires: mvn-JsonPath-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
Jayway JsonPath
=====================
**A Java DSL for reading JSON documents.**

%package data
Summary: data components for the mvn-JsonPath package.
Group: Data

%description data
data components for the mvn-JsonPath package.


%package license
Summary: license components for the mvn-JsonPath package.
Group: Default

%description license
license components for the mvn-JsonPath package.


%prep
%setup -q -n JsonPath-json-path-2.4.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-JsonPath
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-JsonPath/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/jayway/jsonpath/json-path/2.4.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/jayway/jsonpath/json-path/2.4.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.jar
/usr/share/java/.m2/repository/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-JsonPath/LICENSE
